In [2]:
import pandas as pd
import sys
print(sys.version)
print('pandas version', pd.__version__)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
pandas version 2.0.3

# I/O (Reading and writing)

In [3]:
# pd.read_csv, pd.read_excel, pd.read_sql, etc...
df = pd.read_parquet('C:/Users/tkylebjorn/Documents/Python-dataframes/flights.parquet')
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0

In [10]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.to_csv('flights.csv', index=False)

# DataFrame Basics

In [11]:
# This is to set the columns view to a specific number and see more or less columns
pd.set_option('display.max_columns', 500)

In [12]:
# Show the first rows
df.head(10)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
5,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DEN,TUL,False,False,955,952.0,0.0,-3.0,1238.0,0.0,77.0,105.0,106.0,541.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4294,C5,20445,C5,N11191,4294,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,15370,1537002,34653,"Tulsa, OK",OK,40,Oklahoma,73,0.0,-1.0,0900-0959,25.0,1017.0,1234.0,4.0,1240,-2.0,0.0,-1.0,1200-1259,3,0
6,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,LCH,False,False,2139,2136.0,0.0,-3.0,2218.0,0.0,26.0,52.0,42.0,127.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4293,C5,20445,C5,N14143,4293,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,12915,1291503,31205,"Lake Charles, LA",LA,22,Louisiana,72,0.0,-1.0,2100-2159,11.0,2147.0,2213.0,5.0,2231,-13.0,0.0,-1.0,2200-2259,1,0
7,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",TYS,IAH,False,False,1129,1117.0,0.0,-12.0,1311.0,5.0,136.0,157.0,174.0,771.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N13124,4292,15412,1541205,35412,"Knoxville, TN",TN,47,Tennessee,54,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,1100-1159,22.0,1139.0,1255.0,16.0,1306,5.0,0.0,0.0,1300-1359,4,0
8,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,AEX,False,False,1424,1414.0,0.0,-10.0,1513.0,0.0,37.0,60.0,59.0,190.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4291,C5,20445,C5,N33182,4291,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,10185,1018502,30185,"Alexandria, LA",LA,22,Louisiana,72,0.0,-1.0,1400-1459,16.0,1430.0,1507.0,6.0,1524,-11.0,0.0,-1.0,1500-1559,1,0
9,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,MOB,False,False,954,947.0,0.0,-7.0,1110.0,0.0,60.0,87.0,83.0,427.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4290,C5,20445,C5,N21154,4290,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,13422,1342202,30562,"Mobile, AL",AL,1,Alabama,51,0.0,-1.0,0900-0959,17.0,1004.0,1104.0,6.0,1121,-11.0,0.0,-1.0,1100-1159,2,0

In [13]:
# Show the last rows
df.tail(5)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

In [14]:
# Return a random number of rows
df.sample(7)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
320715,2022-06-18,Southwest Airlines Co.,HOU,STL,False,False,540,539.0,0.0,-1.0,729.0,0.0,91.0,115.0,110.0,687.0,2022,2,6,18,6,WN,WN,19393,WN,4439,WN,19393,WN,N8698B,4439,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,15016,1501606,31123,"St. Louis, MO",MO,29,Missouri,64,0.0,-1.0,0001-0559,8.0,547.0,718.0,11.0,735,-6.0,0.0,-1.0,0700-0759,3,0
287968,2022-02-10,Delta Air Lines Inc.,ATL,CHS,False,False,1220,1214.0,0.0,-6.0,1326.0,0.0,45.0,68.0,72.0,259.0,2022,1,2,10,4,DL,DL,19790,DL,2079,DL,19790,DL,N3766,2079,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,10994,1099402,30994,"Charleston, SC",SC,45,South Carolina,37,0.0,-1.0,1200-1259,14.0,1228.0,1313.0,13.0,1328,-2.0,0.0,-1.0,1300-1359,2,0
116281,2022-05-07,United Air Lines Inc.,MCO,EWR,False,False,1218,1221.0,3.0,3.0,1526.0,24.0,143.0,164.0,185.0,937.0,2022,2,5,7,6,UA,UA,19977,UA,1768,UA,19977,UA,N412UA,1768,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,0.0,1200-1259,24.0,1245.0,1508.0,18.0,1502,24.0,1.0,1.0,1500-1559,4,0
173383,2022-01-12,Southwest Airlines Co.,PHX,DAL,False,False,930,936.0,6.0,6.0,1257.0,7.0,126.0,140.0,141.0,879.0,2022,1,1,12,3,WN,WN,19393,WN,4136,WN,19393,WN,N467WN,4136,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,11259,1125904,30194,"Dallas, TX",TX,48,Texas,74,0.0,0.0,0900-0959,12.0,948.0,1254.0,3.0,1250,7.0,0.0,0.0,1200-1259,4,0
364594,2022-03-20,SkyWest Airlines Inc.,EGE,DEN,False,False,1711,1707.0,0.0,-4.0,1806.0,0.0,30.0,59.0,59.0,120.0,2022,1,3,20,7,UA,UA_CODESHARE,19977,UA,5455,OO,20304,OO,N164SY,5455,11503,1150305,31503,"Eagle, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1700-1759,19.0,1726.0,1756.0,10.0,1810,-4.0,0.0,-1.0,1800-1859,1,0
326156,2022-07-27,Endeavor Air Inc.,LGA,PVD,False,False,1000,957.0,0.0,-3.0,1045.0,0.0,28.0,82.0,48.0,143.0,2022,3,7,27,3,DL,DL_CODESHARE,19790,DL,5357,9E,20363,9E,N904XJ,5357,12953,1295304,31703,"New York, NY",NY,36,New York,22,14307,1430705,30721,"Providence, RI",RI,44,Rhode Island,15,0.0,-1.0,1000-1059,17.0,1014.0,1042.0,3.0,1122,-37.0,0.0,-2.0,1100-1159,1,0
408140,2022-04-30,Spirit Air Lines,ACY,MCO,False,False,1637,1900.0,143.0,143.0,2114.0,132.0,111.0,145.0,134.0,852.0,2022,2,4,30,6,NK,NK,20416,NK,1103,NK,20416,NK,N698NK,1103,10158,1015804,30158,"Atlantic City, NJ",NJ,34,New Jersey,21,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,1.0,9.0,1600-1659,16.0,1916.0,2107.0,7.0,1902,132.0,1.0,8.0,1900-1959,4,0

In [15]:
# Show a list of columns and index
df.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [16]:
# Returns the index values in the dataframe
df.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       590532, 590533, 590534, 590535, 590536, 590537, 590538, 590539, 590540,
       590541],
      dtype='int64', length=4078318)

In [17]:
# information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4078318 entries, 0 to 590541
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               datetime64[ns]
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       int64
dtypes: bool(2), datetime64[ns](1), float64(18), int64(23), object(17)
memory usage: 1.8+ GB

In [18]:
# A quicker summary
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 4078318 entries, 0 to 590541
Columns: 61 entries, FlightDate to DivAirportLandings
dtypes: bool(2), datetime64[ns](1), float64(18), int64(23), object(17)
memory usage: 1.8+ GB

In [19]:
# Provide descriptive statistics about the data
df.describe()

,FlightDate,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,DistanceGroup,DivAirportLandings
count,4078318,4.078318e+06,3.957885e+06,3.957823e+06,3.957823e+06,3.954079e+06,3.944916e+06,3.944916e+06,4.078318e+06,3.944916e+06,4.078318e+06,4078318.0,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,3.957823e+06,3.957823e+06,3.955652e+06,3.955652e+06,3.954076e+06,3.954076e+06,4.078318e+06,3.944916e+06,3.944916e+06,3.944916e+06,4.078318e+06,4.078318e+06
mean,2022-04-18 12:10:43.903097600,1.329587e+03,1.334374e+03,1.601494e+01,1.309049e+01,1.457886e+03,1.578307e+01,1.110075e+02,1.413211e+02,1.358624e+02,7.978657e+02,2022.0,1.741207e+00,4.083803e+00,1.571131e+01,4.005566e+00,1.983101e+04,2.562115e+03,1.999122e+04,2.562145e+03,1.265994e+04,1.265998e+06,3.175708e+04,2.746504e+01,5.399368e+01,1.265990e+04,1.265994e+06,3.175704e+04,2.746550e+01,5.399338e+01,2.184625e-01,2.141248e-01,1.697375e+01,1.356576e+03,1.455073e+03,7.894387e+00,1.486058e+03,7.528486e+00,2.164715e-01,-6.256103e-02,3.663516e+00,3.685098e-03
min,2022-01-01 00:00:00,1.000000e+00,1.000000e+00,0.000000e+00,-7.800000e+01,1.000000e+00,0.000000e+00,8.000000e+00,-4.800000e+01,1.400000e+01,3.100000e+01,2022.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,0.000000e+00,-2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+02,0.000000e+00,-2.000000e+00,1.000000e+00,0.000000e+00
25%,2022-02-25 00:00:00,9.140000e+02,9.170000e+02,0.000000e+00,-5.000000e+00,1.046000e+03,0.000000e+00,6.000000e+01,8.900000e+01,8.300000e+01,3.680000e+02,2022.0,1.000000e+00,2.000000e+00,8.000000e+00,2.000000e+00,1.979000e+04,1.105000e+03,1.979000e+04,1.105000e+03,1.129200e+04,1.129202e+06,3.069300e+04,1.200000e+01,3.300000e+01,1.129200e+04,1.129202e+06,3.069300e+04,1.200000e+01,3.300000e+01,0.000000e+00,-1.000000e+00,1.100000e+01,9.320000e+02,1.044000e+03,4.000000e+00,1.103000e+03,-1.400000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,0.000000e+00
50%,2022-04-19 00:00:00,1.320000e+03,1.325000e+03,0.000000e+00,-2.000000e+00,1.500000e+03,0.000000e+00,9.400000e+01,1.240000e+02,1.190000e+02,6.430000e+02,2022.0,2.000000e+00,4.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.228000e+03,1.997700e+04,2.228000e+03,1.288900e+04,1.288903e+06,3.145300e+04,2.700000e+01,4.400000e+01,1.288900e+04,1.288903e+06,3.145300e+04,2.700000e+01,4.400000e+01,0.000000e+00,-1.000000e+00,1.500000e+01,1.338000e+03,1.456000e+03,6.000000e+00,1.513000e+03,-5.000000e+00,0.000000e+00,-1.000000e+00,3.000000e+00,0.000000e+00
75%,2022-06-11 00:00:00,1.735000e+03,1.744000e+03,1.100000e+01,1.100000e+01,1.914000e+03,1.000000e+01,1.410000e+02,1.710000e+02,1.670000e+02,1.035000e+03,2022.0,2.000000e+00,6.000000e+00,2.300000e+01,6.000000e+00,1.997700e+04,3.877000e+03,2.037800e+04,3.877000e+03,1.402700e+04,1.402702e+06,3.246700e+04,4.200000e+01,8.100000e+01,1.402700e+04,1.402702e+06,3.246700e+04,4.200000e+01,8.100000e+01,0.000000e+00,0.000000e+00,1.900000e+01,1.758000e+03,1.909000e+03,9.000000e+00,1.920000e+03,1.000000e+01,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00
max,2022-07-31 00:00:00,2.359000e+03,2.400000e+03,7.223000e+03,7.223000e+03,2.400000e+03,7.232000e+03,7.270000e+02,6.900000e+02,7.640000e+02,5.095000e+03,2022.0,3.000000e+00,7.000000e+00,3.100000e+01,7.000000e+00,2.043600e+04,9.680000e+03,2.050000e+04,9.680000e+03,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.000000e+00,1.200000e+01,2.210000e+02,2.400000e+03,2.400000e+03,2.900000e+02,2.359000e+03,7.232000e+03,1.000000e+00,1.200000e+01,1.100000e+01,9.000000e+00
std,NaN,4.904801e+02,5.056219e+02,5.231498e+01,5.332016e+01,5.431841e+02,5.198424e+01,6.996246e+01,7.179635e+01,7.185501e+01,5.914742e+02,0.0,7.037563e-01,1.998918e+00,8.760122e+00,2.007050e+00,2.760907e+02,1.745826e+03,3.767694e+02,1.745873e+03,1.522713e+03,1.522711e+05,1.320296e+03,1.670547e+01,2.664820e+01,1.522718e+03,1.522716e+05,1.320286e+03,1.670567e+01,2.664849e+01,4.132030e-01,2.345973e+00,9.495407e+00,5.075580e+02,5.378428e+02,6.663118e+00,5.185078e+02,5.524625e+01,4.118393e-01,2.487442e+00,2.320848e+00,1.141331e-01

In [20]:
# also works on non-numeric columns
df[['Airline']].describe()

                       Airline
count                  4078318
unique                      21
top     Southwest Airlines Co.
freq                    731925

In [22]:
# return the shape of the dataframe
df.shape, len(df)

((4078318, 61), 4078318)

Subsetting a dataframe

In [23]:
# this process is often done. Sometimes we want to filter down the columns
df[['FlightDate', 'Airline', 'Origin']]

       FlightDate                                    Airline Origin
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    IAH
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
...           ...                                        ...    ...
590537 2022-03-31                          Republic Airlines    MSY
590538 2022-03-17                          Republic Airlines    CLT
590539 2022-03-08                          Republic Airlines    ALB
590540 2022-03-25                          Republic Airlines    EWR
590541 2022-03-07                          Republic Airlines    EWR

[4078318 rows x 3 columns]

In [26]:
#subsetting using slicing
df[df.columns[:5]]

,FlightDate,Airline,Origin,Dest,Cancelled
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False
590538,2022-03-17,Republic Airlines,CLT,EWR,True
590539,2022-03-08,Republic Airlines,ALB,ORD,False
590540,2022-03-25,Republic Airlines,EWR,PIT,False
590541,2022-03-07,Republic Airlines,EWR,RDU,False

In [28]:
# selecting columns from the DataFrame df that have 'Time' in their names and creating a new DataFrame with only those columns.
df[[c for c in df.columns if 'Time' in c]]

,CRSDepTime,DepTime,ArrTime,AirTime,CRSElapsedTime,ActualElapsedTime,DepTimeBlk,CRSArrTime,ArrTimeBlk
0,1133,1123.0,1228.0,40.0,72.0,65.0,1100-1159,1245,1200-1259
1,732,728.0,848.0,55.0,77.0,80.0,0700-0759,849,0800-0859
2,1529,1514.0,1636.0,47.0,70.0,82.0,1500-1559,1639,1600-1659
3,1435,1430.0,1547.0,57.0,90.0,77.0,1400-1459,1605,1600-1659
4,1135,1135.0,1251.0,49.0,70.0,76.0,1100-1159,1245,1200-1259
...,...,...,...,...,...,...,...,...,...
590537,1949,2014.0,234.0,NaN,185.0,NaN,1900-1959,2354,2300-2359
590538,1733,1817.0,NaN,NaN,129.0,NaN,1700-1759,1942,1900-1959
590539,1700,2318.0,59.0,135.0,158.0,161.0,1700-1759,1838,1800-1859
590540,2129,2322.0,939.0,NaN,86.0,NaN,2100-2159,2255,2200-2259
590541,1154,1148.0,1556.0,NaN,99.0,NaN,1100-1159,1333,1300-1359

In [30]:
# selecting columns by data types
df.select_dtypes('int')

,CRSDepTime,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,CRSArrTime,DistanceGroup,DivAirportLandings
0,1133,2022,2,4,4,1,19977,4301,20445,4301,11921,1192102,31921,8,82,11292,1129202,30325,8,82,1245,1,0
1,732,2022,2,4,4,1,19977,4299,20445,4299,12206,1220605,32206,48,74,12266,1226603,31453,48,74,849,2,0
2,1529,2022,2,4,4,1,19977,4298,20445,4298,11413,1141307,30285,8,82,11292,1129202,30325,8,82,1639,2,0
3,1435,2022,2,4,4,1,19977,4296,20445,4296,12266,1226603,31453,48,74,11973,1197302,31973,28,53,1605,2,0
4,1135,2022,2,4,4,1,19977,4295,20445,4295,11413,1141307,30285,8,82,11292,1129202,30325,8,82,1245,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,1949,2022,1,3,31,4,19977,3621,20452,3621,13495,1349505,33495,22,72,11618,1161802,31703,34,21,2354,5,1
590538,1733,2022,1,3,17,4,19977,3437,20452,3437,11057,1105703,31057,37,36,11618,1161802,31703,34,21,1942,3,0
590539,1700,2022,1,3,8,2,19977,3413,20452,3413,10257,1025702,30257,36,22,13930,1393007,30977,17,41,1838,3,0
590540,2129,2022,1,3,25,5,19977,3450,20452,3450,11618,1161802,31703,34,21,14122,1412202,30198,42,23,2255,2,1
590541,1154,2022,1,3,7,1,19977,3585,20452,3585,11618,1161802,31703,34,21,14492,1449202,34492,37,36,1333,2,1

In [33]:
#use a pair of square brackets to return the series of a dataframe
#use two pair brackets to return a dataframe view
df[['Airline']]

                                          Airline
0       Commutair Aka Champlain Enterprises, Inc.
1       Commutair Aka Champlain Enterprises, Inc.
2       Commutair Aka Champlain Enterprises, Inc.
3       Commutair Aka Champlain Enterprises, Inc.
4       Commutair Aka Champlain Enterprises, Inc.
...                                           ...
590537                          Republic Airlines
590538                          Republic Airlines
590539                          Republic Airlines
590540                          Republic Airlines
590541                          Republic Airlines

[4078318 rows x 1 columns]

# Filtering Rows
df.loc[] and df.iloc[]

df.iloc[] uses the index location
df.loc[] uses the names

In [34]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0

In [37]:
# if we want to pull up the second row and the fourth column (IAH) using iloc
df.iloc[1,3]

'IAH'

In [39]:
# getting the row information we select
df.iloc[2]

FlightDate                                  2022-04-04 00:00:00
Airline               Commutair Aka Champlain Enterprises, Inc.
Origin                                                      DRO
Dest                                                        DEN
Cancelled                                                 False
                                        ...
ArrDel15                                                    0.0
ArrivalDelayGroups                                         -1.0
ArrTimeBlk                                            1600-1659
DistanceGroup                                                 2
DivAirportLandings                                            0
Name: 2, Length: 61, dtype: object

In [41]:
# returns the dataframe by selecting the data "spirit air lines" only in the airline column
df.loc[df['Airline'] == 'Spirit Air Lines']

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
407040,2022-04-01,Spirit Air Lines,FLL,ORD,True,False,2025,NaN,NaN,NaN,NaN,NaN,NaN,193.0,NaN,1182.0,2022,2,4,1,5,NK,NK,20416,NK,1,NK,20416,NK,N669NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2238,NaN,NaN,NaN,2200-2259,5,0
407041,2022-04-02,Spirit Air Lines,FLL,ORD,True,False,2147,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,1182.0,2022,2,4,2,6,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2100-2159,NaN,NaN,NaN,NaN,2359,NaN,NaN,NaN,2300-2359,5,0
407042,2022-04-03,Spirit Air Lines,FLL,ORD,False,False,2147,211.0,264.0,264.0,421.0,262.0,163.0,192.0,190.0,1182.0,2022,2,4,3,7,NK,NK,20416,NK,1,NK,20416,NK,N661NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,2100-2159,18.0,229.0,412.0,9.0,2359,262.0,1.0,12.0,2300-2359,5,0
407043,2022-04-04,Spirit Air Lines,FLL,ORD,False,False,2147,2227.0,40.0,40.0,39.0,40.0,157.0,192.0,192.0,1182.0,2022,2,4,4,1,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,2.0,2100-2159,25.0,2252.0,29.0,10.0,2359,40.0,1.0,2.0,2300-2359,5,0
407044,2022-04-05,Spirit Air Lines,FLL,ORD,False,False,2200,2252.0,52.0,52.0,58.0,46.0,164.0,192.0,186.0,1182.0,2022,2,4,5,2,NK,NK,20416,NK,1,NK,20416,NK,N681NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,3.0,2200-2259,13.0,2305.0,49.0,9.0,12,46.0,1.0,3.0,0001-0559,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142478,2022-03-27,Spirit Air Lines,EWR,LAS,False,False,1700,1705.0,5.0,5.0,2019.0,58.0,297.0,321.0,374.0,2227.0,2022,1,3,27,7,NK,NK,20416,NK,993,NK,20416,NK,N693NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,69.0,1814.0,2011.0,8.0,1921,58.0,1.0,3.0,1900-1959,9,0
142479,2022-03-28,Spirit Air Lines,EWR,LAS,False,False,1700,1802.0,62.0,62.0,2043.0,82.0,312.0,321.0,341.0,2227.0,2022,1,3,28,1,NK,NK,20416,NK,993,NK,20416,NK,N641NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,24.0,1826.0,2038.0,5.0,1921,82.0,1.0,5.0,1900-1959,9,0
142480,2022-03-29,Spirit Air Lines,EWR,LAS,False,False,1700,1654.0,0.0,-6.0,1912.0,0.0,300.0,321.0,318.0,2227.0,2022,1,3,29,2,NK,NK,20416,NK,993,NK,20416,NK,N623NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,1700-1759,11.0,1705.0,1905.0,7.0,1921,-9.0,0.0,-1.0,1900-1959,9,0
142481,2022-03-30,Spirit Air Lines,EWR,LAS,False,False,1700,1709.0,9.0,9.0,2004.0,43.0,296.0,321.0,355.0,2227.0,2022,1,3,30,3,NK,NK,20416,NK,993,NK,20416,NK,N645NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,52.0,1801.0,1957.0,7.0,1921,43.0,1.0,2.0,1900-1959,9,0
142482,2022-03-31,Spirit Air Lines,EWR,LAS,True,False,1700,1804.0,64.0,64.0,NaN,NaN,NaN,321.0,NaN,2227.0,2022,1,3,31,4,NK,NK,20416,NK,993,NK,20416,NK,N650NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,NaN,NaN,NaN,NaN,1921,NaN,NaN,NaN,1900-1959,9,0

In [43]:
# returns the dataframe by selecting the data "spirit air lines" and "flights on 
#14 may 2022" in the airline and flightdate columns
##boolean expresions work like this
df.loc[(df['Airline'] == 'Spirit Air Lines')
        & (df['FlightDate'] == '2022-05-14')
]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
419542,2022-05-14,Spirit Air Lines,FLL,ORD,False,False,710,709.0,0.0,-1.0,935.0,11.0,162.0,194.0,206.0,1182.0,2022,2,5,14,6,NK,NK,20416,NK,1,NK,20416,NK,N673NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0700-0759,33.0,742.0,924.0,11.0,924,11.0,0.0,0.0,0900-0959,5,0
419573,2022-05-14,Spirit Air Lines,ORD,FLL,False,False,505,510.0,5.0,5.0,909.0,4.0,151.0,180.0,179.0,1182.0,2022,2,5,14,6,NK,NK,20416,NK,2,NK,20416,NK,N658NK,2,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,0.0,0001-0559,20.0,530.0,901.0,8.0,905,4.0,0.0,0.0,0900-0959,5,0
419604,2022-05-14,Spirit Air Lines,ORD,FLL,False,False,755,806.0,11.0,11.0,1151.0,0.0,150.0,182.0,165.0,1182.0,2022,2,5,14,6,NK,NK,20416,NK,3,NK,20416,NK,N671NK,3,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,0.0,0700-0759,10.0,816.0,1146.0,5.0,1157,-6.0,0.0,-1.0,1100-1159,5,0
419635,2022-05-14,Spirit Air Lines,FLL,ORD,False,False,1715,1810.0,55.0,55.0,2020.0,52.0,170.0,193.0,190.0,1182.0,2022,2,5,14,6,NK,NK,20416,NK,6,NK,20416,NK,N658NK,6,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,3.0,1700-1759,10.0,1820.0,2010.0,10.0,1928,52.0,1.0,3.0,1900-1959,5,0
419663,2022-05-14,Spirit Air Lines,ATL,MSP,False,False,755,752.0,0.0,-3.0,917.0,0.0,124.0,154.0,145.0,907.0,2022,2,5,14,6,NK,NK,20416,NK,40,NK,20416,NK,N530NK,40,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,0.0,-1.0,0700-0759,12.0,804.0,908.0,9.0,929,-12.0,0.0,-1.0,0900-0959,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438459,2022-05-14,Spirit Air Lines,SMF,LAS,False,False,530,525.0,0.0,-5.0,645.0,0.0,61.0,84.0,80.0,397.0,2022,2,5,14,6,NK,NK,20416,NK,979,NK,20416,NK,N942NK,979,14893,1489302,33192,"Sacramento, CA",CA,6,California,91,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,0001-0559,15.0,540.0,641.0,4.0,654,-9.0,0.0,-1.0,0600-0659,2,0
438489,2022-05-14,Spirit Air Lines,CLT,FLL,False,False,1840,1837.0,0.0,-3.0,2102.0,22.0,120.0,120.0,145.0,632.0,2022,2,5,14,6,NK,NK,20416,NK,980,NK,20416,NK,N955NK,980,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,-1.0,1800-1859,17.0,1854.0,2054.0,8.0,2040,22.0,1.0,1.0,2000-2059,3,0
438519,2022-05-14,Spirit Air Lines,FLL,CLT,False,False,1520,1522.0,2.0,2.0,1714.0,0.0,92.0,120.0,112.0,632.0,2022,2,5,14,6,NK,NK,20416,NK,981,NK,20416,NK,N955NK,981,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,0.0,0.0,1500-1559,17.0,1539.0,1711.0,3.0,1720,-6.0,0.0,-1.0,1700-1759,3,0
438546,2022-05-14,Spirit Air Lines,DTW,MSY,False,False,550,548.0,0.0,-2.0,707.0,0.0,118.0,151.0,139.0,926.0,2022,2,5,14,6,NK,NK,20416,NK,985,NK,20416,NK,N694NK,985,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,0.0,-1.0,0001-0559,14.0,602.0,700.0,7.0,721,-14.0,0.0,-1.0,0700-0759,4,0
438600,2022-05-14,Spirit Air Lines,EWR,LAS,False,False,719,718.0,0.0,-1.0,944.0,0.0,295.0,325.0,326.0,2227.0,2022,2,5,14,6,NK,NK,20416,NK,993,NK,20416,NK,N903NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,0700-0759,16.0,734.0,929.0,15.0,944,0.0,0.0,0.0,0900-0959,9,0

In [47]:
#using the reverse of the same expression (returning any value but these)
df.loc[
~((df['Airline'] == 'Spirit Air Lines') 
         & (df['FlightDate'] == '2022-05-14'))
]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

# Filtering using Query

In [50]:
# takes in a string representation of the boolean expression
df.query('DepTime > 1130')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
6,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,LCH,False,False,2139,2136.0,0.0,-3.0,2218.0,0.0,26.0,52.0,42.0,127.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4293,C5,20445,C5,N14143,4293,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,12915,1291503,31205,"Lake Charles, LA",LA,22,Louisiana,72,0.0,-1.0,2100-2159,11.0,2147.0,2213.0,5.0,2231,-13.0,0.0,-1.0,2200-2259,1,0
8,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,AEX,False,False,1424,1414.0,0.0,-10.0,1513.0,0.0,37.0,60.0,59.0,190.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4291,C5,20445,C5,N33182,4291,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,10185,1018502,30185,"Alexandria, LA",LA,22,Louisiana,72,0.0,-1.0,1400-1459,16.0,1430.0,1507.0,6.0,1524,-11.0,0.0,-1.0,1500-1559,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

In [57]:
# adding more values and accessing a variable using @
min_time = 1130
df.query('(DepTime > @min_time) and (Origin == "DRO")')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
531,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1524.0,0.0,-5.0,1633.0,0.0,50.0,70.0,69.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N11191,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,9.0,1533.0,1623.0,10.0,1639,-6.0,0.0,-1.0,1600-1659,2,0
533,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1134.0,0.0,-1.0,1247.0,2.0,43.0,70.0,73.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N31131,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,19.0,1153.0,1236.0,11.0,1245,2.0,0.0,0.0,1200-1259,2,0
1003,2022-04-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1644.0,75.0,75.0,1757.0,78.0,46.0,70.0,73.0,251.0,2022,2,4,2,6,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N16151,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,5.0,1500-1559,15.0,1659.0,1745.0,12.0,1639,78.0,1.0,5.0,1600-1659,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445339,2022-03-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1521.0,0.0,-9.0,1645.0,5.0,50.0,70.0,84.0,251.0,2022,1,3,3,4,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N12163,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,27.0,1548.0,1638.0,7.0,1640,5.0,0.0,0.0,1600-1659,2,0
445977,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1531.0,1.0,1.0,1651.0,11.0,50.0,70.0,80.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N33182,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1500-1559,19.0,1550.0,1640.0,11.0,1640,11.0,0.0,0.0,1600-1659,2,0
445986,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1142.0,7.0,7.0,1245.0,0.0,46.0,70.0,63.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N33182,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,11.0,1153.0,1239.0,6.0,1245,0.0,0.0,0.0,1200-1259,2,0
446617,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1741.0,131.0,131.0,1909.0,149.0,52.0,70.0,88.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N16178,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,8.0,1500-1559,25.0,1806.0,1858.0,11.0,1640,149.0,1.0,9.0,1600-1659,2,0
446626,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1419.0,164.0,164.0,1523.0,158.0,46.0,70.0,64.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N14174,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,10.0,1100-1159,11.0,1430.0,1516.0,7.0,1245,158.0,1.0,10.0,1200-1259,2,0

# Summarizing Data

df['DepTime'].min()
mean
min
max
std
var
count
sum
quantile (can also take a list)

In [60]:
#running one statistics method using some columns
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].min()

DepTime       1.0
DepDelay    -78.0
ArrTime       1.0
ArrDelay   -100.0
dtype: float64

In [61]:
# several statistics methods
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(['mean', 'min', 'max'])

          DepTime     DepDelay      ArrTime     ArrDelay
mean  1334.373931    13.090487  1457.886018     7.528486
min      1.000000   -78.000000     1.000000  -100.000000
max   2400.000000  7223.000000  2400.000000  7232.000000

In [62]:
# several statistics methods using a dictionary
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(
    {'DepTime' : ['min', 'max'],
     'DepDelay' : ['mean'],
     'ArrTime' : ['min', 'max']
    }
)

      DepTime   DepDelay  ArrTime
min       1.0        NaN      1.0
max    2400.0        NaN   2400.0
mean      NaN  13.090487      NaN

# Summarizing Categorial Variables

In [63]:
# returns an array of unique fields
df['Airline'].unique()

array(['Commutair Aka Champlain Enterprises, Inc.',
       'GoJet Airlines, LLC d/b/a United Express',
       'Air Wisconsin Airlines Corp', 'Mesa Airlines Inc.',
       'Southwest Airlines Co.', 'Republic Airlines', 'Endeavor Air Inc.',
       'American Airlines Inc.', 'Capital Cargo International',
       'SkyWest Airlines Inc.', 'Alaska Airlines Inc.', 'JetBlue Airways',
       'Delta Air Lines Inc.', 'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Spirit Air Lines',
       'Comair Inc.', 'Horizon Air', 'United Air Lines Inc.'],
      dtype=object)

In [64]:
# returns the number of counts in that field
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       731925
Delta Air Lines Inc.                         512114
American Airlines Inc.                       495953
SkyWest Airlines Inc.                        440807
United Air Lines Inc.                        352009
Republic Airlines                            197881
JetBlue Airways                              156793
Envoy Air                                    150758
Endeavor Air Inc.                            142624
Comair Inc.                                  135884
Alaska Airlines Inc.                         129510
Spirit Air Lines                             129208
Frontier Airlines Inc.                        86557
Allegiant Air                                 73504
Mesa Airlines Inc.                            71972
Horizon Air                                   56320
Capital Cargo International                   52827
Commutair Aka Champlain Enterprises, Inc.     44367
Hawaiian Airlines Inc.                        42212
Air Wisconsin Airlines Corp                   40300
GoJet Airlines, LLC d/b/a United Express      34793
Name: count, dtype: int64

In [66]:
# selecting various columns and making it a dataframe with reset_index()
df[['Airline', 'Origin']].value_counts().reset_index()

                                        Airline Origin   count
0                          Delta Air Lines Inc.    ATL  120919
1                        American Airlines Inc.    DFW   81239
2                        American Airlines Inc.    CLT   57914
3                         United Air Lines Inc.    DEN   46489
4                        Southwest Airlines Co.    DEN   45398
...                                         ...    ...     ...
2189                     Frontier Airlines Inc.    ICT       1
2190                         Mesa Airlines Inc.    MDT       1
2191                Air Wisconsin Airlines Corp    FWA       1
2192  Commutair Aka Champlain Enterprises, Inc.    DSM       1
2193   GoJet Airlines, LLC d/b/a United Express    MKE       1

[2194 rows x 3 columns]

# Advanced Column Methods

In [70]:
df[['CRSDepTime']]

        CRSDepTime
0             1133
1              732
2             1529
3             1435
4             1135
...            ...
590537        1949
590538        1733
590539        1700
590540        2129
590541        1154

[4078318 rows x 1 columns]

In [71]:
# multiple values for the same rank using dense
df[['CRSDepTime']].rank(method='dense')

        CRSDepTime
0            574.0
1            333.0
2            810.0
3            756.0
4            576.0
...            ...
590537      1070.0
590538       934.0
590539       901.0
590540      1170.0
590541       595.0

[4078318 rows x 1 columns]

In [72]:
# multiple values for the same rank using first
df[['CRSDepTime']].rank(method='first')

        CRSDepTime
0        1607043.0
1         594869.0
2        2547637.0
3        2338954.0
4        1610842.0
...            ...
590537   3576966.0
590538   3054522.0
590539   2925978.0
590540   3879124.0
590541   1679890.0

[4078318 rows x 1 columns]

In [82]:
# this function will shift all the values in that column by a provided number
df[['CRSDepTime']].shift(0)

        CRSDepTime
0             1133
1              732
2             1529
3             1435
4             1135
...            ...
590537        1949
590538        1733
590539        1700
590540        2129
590541        1154

[4078318 rows x 1 columns]

In [77]:
# cumulative sum over a seris or dataframe
df[['CRSDepTime']].cumsum()

        CRSDepTime
0             1133
1             1865
2             3394
3             4829
4             5964
...            ...
590537  5422470512
590538  5422472245
590539  5422473945
590540  5422476074
590541  5422477228

[4078318 rows x 1 columns]

In [ ]:
# cumulative max
df[['CRSDepTime']].cummax()

In [ ]:
# cumulative min
df[['CRSDepTime']].cummin()

# Rolling Methods

In [84]:
# The rolling window moves through the data, and for each position, the function is applied to 
#the data within that window
# useful with time series data
df[['DepDelayMinutes']].rolling(window=5).mean()

        DepDelayMinutes
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   0.0
...                 ...
590537            144.2
590538            108.4
590539            145.0
590540            142.8
590541            112.0

[4078318 rows x 1 columns]

In [88]:
# limits the values in a DataFrame or Series to be within a specified range and replaces them
df['DepTime'].clip(1000,2000)

0         1123.0
1         1000.0
2         1514.0
3         1430.0
4         1135.0
           ...
590537    2000.0
590538    1817.0
590539    2000.0
590540    2000.0
590541    1148.0
Name: DepTime, Length: 4078318, dtype: float64

# Groupby Methods

In [90]:
# group by Airlines and measure its average time in Depature delay
df.groupby('Airline')[['DepDelay']].mean()

                                            DepDelay
Airline
Air Wisconsin Airlines Corp                 7.913244
Alaska Airlines Inc.                        5.925950
Allegiant Air                              19.061569
American Airlines Inc.                     14.876556
Capital Cargo International                 6.044430
Comair Inc.                                12.693968
Commutair Aka Champlain Enterprises, Inc.  12.093640
Delta Air Lines Inc.                       11.398599
Endeavor Air Inc.                           9.696390
Envoy Air                                   6.883448
Frontier Airlines Inc.                     20.052761
GoJet Airlines, LLC d/b/a United Express   16.741980
Hawaiian Airlines Inc.                      6.612163
Horizon Air                                 5.892804
JetBlue Airways                            26.009890
Mesa Airlines Inc.                         15.714753
Republic Airlines                          10.811487
SkyWest Airlines Inc.                      11.247036
Southwest Airlines Co.                     14.563121
Spirit Air Lines                           15.621816
United Air Lines Inc.                      13.730542

In [9]:
# multiple statistics using agg and multiple columns
df_agg = df.groupby('Airline')[['DepDelay', 'ArrDelay']].agg(['mean', 'min', 'max'])

In [10]:
# use list comprehension to rename the columns
df_agg.columns = ['_'.join(c) for c in df_agg.columns]

In [11]:
df_agg

,DepDelay_mean,DepDelay_min,DepDelay_max,ArrDelay_mean,ArrDelay_min,ArrDelay_max
Airline,,,,,,
Air Wisconsin Airlines Corp,7.913244,-30.0,1355.0,1.819183,-63.0,1353.0
Alaska Airlines Inc.,5.925950,-63.0,915.0,3.170588,-76.0,908.0
Allegiant Air,19.061569,-37.0,1917.0,20.519645,-69.0,1919.0
American Airlines Inc.,14.876556,-35.0,2994.0,9.528696,-80.0,2977.0
Capital Cargo International,6.044430,-34.0,1512.0,2.627024,-52.0,1490.0
Comair Inc.,12.693968,-49.0,1607.0,9.339501,-65.0,1612.0
"Commutair Aka Champlain Enterprises, Inc.",12.093640,-27.0,1464.0,8.018588,-62.0,1456.0
Delta Air Lines Inc.,11.398599,-38.0,1287.0,3.925805,-86.0,1285.0
Endeavor Air Inc.,9.696390,-34.0,1973.0,4.164953,-61.0,1968.0
Envoy Air,6.883448,-29.0,5327.0,2.381778,-60.0,5324.0
Frontier Airlines Inc.,20.052761,-40.0,1288.0,17.218371,-72.0,1311.0
"GoJet Airlines, LLC d/b/a United Express",16.741980,-43.0,1220.0,12.887419,-58.0,1199.0
Hawaiian Airlines Inc.,6.612163,-32.0,1847.0,4.489443,-65.0,1805.0
Horizon Air,5.892804,-38.0,803.0,4.278277,-41.0,803.0
JetBlue Airways,26.009890,-56.0,2052.0,20.009015,-100.0,2029.0
Mesa Airlines Inc.,15.714753,-35.0,1837.0,8.766944,-77.0,1818.0
Republic Airlines,10.811487,-55.0,7223.0,7.208726,-81.0,7232.0
SkyWest Airlines Inc.,11.247036,-55.0,2366.0,5.964007,-73.0,2363.0
Southwest Airlines Co.,14.563121,-52.0,747.0,7.176226,-69.0,731.0
Spirit Air Lines,15.621816,-39.0,1436.0,12.234907,-55.0,1436.0
United Air Lines Inc.,13.730542,-78.0,1520.0,6.624249,-75.0,1496.0

# New Columns

In [16]:
df['DepTime2'] = df['DepTime'] / 60
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0,18.716667
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0,12.133333
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0,25.233333
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0,23.833333
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0,18.916667

In [18]:
df.assign(DepTime2 = df['DepTime'] / 60)
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0,18.716667
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0,12.133333
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0,25.233333
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0,23.833333
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0,18.916667

# Sorting Data

In [20]:
df.sort_values('FlightDate')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
428764,2022-01-01,SkyWest Airlines Inc.,DEN,LAX,False,False,600,852.0,172.0,172.0,...,1042.0,7.0,756,173.0,1.0,11.0,0700-0759,4,0,14.200000
160310,2022-01-01,Southwest Airlines Co.,BDL,BNA,False,False,1430,1428.0,0.0,-2.0,...,1608.0,10.0,1610,8.0,0.0,0.0,1600-1659,4,0,23.800000
160311,2022-01-01,Southwest Airlines Co.,BDL,BWI,False,False,1235,1313.0,38.0,38.0,...,1421.0,5.0,1350,36.0,1.0,2.0,1300-1359,2,0,21.883333
160312,2022-01-01,Southwest Airlines Co.,BDL,BWI,False,False,525,531.0,6.0,6.0,...,633.0,20.0,645,8.0,0.0,0.0,0600-0659,2,0,8.850000
160313,2022-01-01,Southwest Airlines Co.,BDL,BWI,True,False,1710,NaN,NaN,NaN,...,NaN,NaN,1830,NaN,NaN,NaN,1800-1859,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360374,2022-07-31,American Airlines Inc.,LAX,MIA,False,False,625,623.0,0.0,-2.0,...,1436.0,9.0,1450,-5.0,0.0,-1.0,1400-1459,10,0,10.383333
296799,2022-07-31,Spirit Air Lines,CLE,MCO,False,False,1830,1824.0,0.0,-6.0,...,2035.0,8.0,2100,-17.0,0.0,-2.0,2100-2159,4,0,30.400000
578752,2022-07-31,Southwest Airlines Co.,AUS,MCO,False,False,1615,1616.0,1.0,1.0,...,1940.0,13.0,1950,3.0,0.0,0.0,1900-1959,4,0,26.933333
412860,2022-07-31,Capital Cargo International,PHL,LEX,False,False,1530,1521.0,0.0,-9.0,...,1719.0,4.0,1723,0.0,0.0,0.0,1700-1759,3,0,25.350000
277622,2022-07-31,Envoy Air,ALO,ORD,False,False,1829,1818.0,0.0,-11.0,...,1915.0,14.0,1945,-16.0,0.0,-2.0,1900-1959,1,0,30.300000

In [22]:
# Selecting columns and sorting by ArrDelay descending and resetting the index number of it
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False).reset_index(drop=True)

        FlightDate                 Airline  ArrDelay
0       2022-05-23       Republic Airlines    7232.0
1       2022-06-18               Envoy Air    5324.0
2       2022-05-16       Republic Airlines    4318.0
3       2022-06-05  American Airlines Inc.    2977.0
4       2022-03-26  American Airlines Inc.    2934.0
...            ...                     ...       ...
4078313 2022-03-31       Republic Airlines       NaN
4078314 2022-03-31       Republic Airlines       NaN
4078315 2022-03-17       Republic Airlines       NaN
4078316 2022-03-25       Republic Airlines       NaN
4078317 2022-03-07       Republic Airlines       NaN

[4078318 rows x 3 columns]

# Handling Missing Data

In [23]:
#visualizing missing data first
df[['FlightDate', 'Airline', 'ArrDelay']].isna()

        FlightDate  Airline  ArrDelay
0            False    False     False
1            False    False     False
2            False    False     False
3            False    False     False
4            False    False     False
...            ...      ...       ...
590537       False    False      True
590538       False    False      True
590539       False    False     False
590540       False    False      True
590541       False    False      True

[4078318 rows x 3 columns]

In [24]:
# returns how many NAs we have in the columns we select
df[['FlightDate', 'Airline', 'ArrDelay']].isna().sum()

FlightDate         0
Airline            0
ArrDelay      133402
dtype: int64

In [ ]:
# this deletes every row that contains missing data
df[['FlightDate', 'Airline', 'ArrDelay']].dropna()

In [ ]:
# subsetting this will only drop the NAs from that column only
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset = ['ArrDelay'])

In [ ]:
# this fills NA values with whatever you want to assign it
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(0)

In [25]:
# filling NA with average value
df['ArrDelay'].fillna(df['ArrDelay'].mean())

0         -17.000000
1          -1.000000
2          -3.000000
3         -18.000000
4           6.000000
             ...
590537      7.528486
590538      7.528486
590539    381.000000
590540      7.528486
590541      7.528486
Name: ArrDelay, Length: 4078318, dtype: float64

# Combining Data

In [29]:
# whenever we create a new dataset like this that we want to be independent from our original dataset we need to run copy()
df1 = df.query('Airline == "American Airlines Inc."').copy()
df2 = df.query('Airline == "Envoy Air"').copy()

df_stack = pd.concat([df1, df2])

df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

df_side = pd.concat([df1, df2], axis = 1)

In [30]:
df1.shape, df2.shape, df_stack.shape, df_side.shape

((495953, 62), (150758, 62), (646711, 62), (495953, 124))

# Merge Data

In [31]:
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [ ]:
# this will take any similar columns between the 2 datasets and combine on those
df1.merge(df2, how='inner')

In [32]:
# if there are columns with the same name on both df, the system will automatically rename those columns
# by adding _x or _y suffixes
pd.merge(df1, df2, on = ['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857

In [39]:
# we can change the suffixes as we want using
pd.merge(df1, df2, on = ['Airline'], suffixes = ('_dep', '_arr'))

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857

In [40]:
# if the dataframes are different we can use left_on and right_on
pd.merge(df1, df2, left_on = ['Airline'], right_on = ['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857